language: node_js
dist: trusty
node_js:
  - '10.10.0'

cache:
  directories:
    - node_modules

sudo: required
addons:
  chrome: stable

install:
  - npm install -g @angular/cli
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run e2e
  - npm run build
